### ISSUE TITLE
Please add special command: Restart Audio Engine

### ISSUE THREAD

**Issue by JWise1203** [onyx-and-iris/voicemeeter-api-powershell#1]
I have a need to run the Restart Audio Engine command in an automated way.

From page 8 in Remote API Guide:

Command Name -  Command.Restart
Value Range -  1
Remark -  Restart Audio Engine
Version -  1

**Comment by onyx-and-iris** [comment]
Hi, thanks for the message. I will look into this for you tomorrow.

**Comment by onyx-and-iris** [comment]
[https://github.com/onyx-and-iris/voicemeeter-api-powershell/commit/a7913f89340b1d7be7425790c84a43edd1a793d8](url)

This should work for you mate.
