### ISSUE TITLE
Implement Command.Load

### ISSUE THREAD

**Issue by kaijen** [onyx-and-iris/voicemeeter-api-powershell#3]
Thx for the great wrapper around the VB API. Could you please implement `Command.Load` (Page 8 Voice API Documentation).

**Comment by onyx-and-iris** [comment]
Hey, thanks for your interest in the code.

I've pushed a commit that implements a Load function into Command class.

I have further updates to make in the near future so I will wait until I make those before pushing the changes to PSGallery. You may use source files until then.

Alternatively, you could also use `$vmr.Setter()` as well. 

example:

```powershell
$_.Setter("Command.Load", "path\to\config.xml")
```

**Comment by kaijen** [comment]
Thank you very much for your support and the explanation!
